# Generated by Django 4.2.1 on 2023-05-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_details_id', models.IntegerField()),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('contact_details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_number', models.BigIntegerField()),
                ('alternate_mobile_number', models.BigIntegerField()),
                ('email_identifier', models.EmailField(max_length=254)),
                ('alternate_email_identifier', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('res_code', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('personal_id', models.IntegerField()),
                ('claim_status', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=50)),
                ('res_first_name', models.CharField(max_length=80)),
                ('res_last_name', models.CharField(max_length=50)),
                ('res_middle_name', models.CharField(blank=True, max_length=50)),
                ('res_name_prefix', models.CharField(blank=True, choices=[('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], max_length=50)),
                ('res_name_suffix', models.CharField(blank=True, max_length=10)),
                ('res_age', models.PositiveIntegerField()),
                ('res_weight', models.PositiveIntegerField()),
                ('res_height', models.PositiveIntegerField()),
                ('res_image', models.ImageField(blank=True, upload_to='personal_images/')),
                ('res_marital_status', models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], max_length=10)),
                ('res_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('res_is_handicap', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=50)),
                ('res_date_of_birth', models.DateField()),
                ('res_occupation', models.CharField(blank=True, max_length=50)),
                ('res_aadhar_card_number', models.BigIntegerField(blank=True)),
                ('res_aadhar_card_image', models.ImageField(blank=True, upload_to='aadhar_card_images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('address_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS_patient_registration.addressdetails')),
                ('contact_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS_patient_registration.contactdetails')),
            ],
        ),
    ]
