# Generated by Django 4.2.1 on 2023-05-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('service_provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_provider_name', models.CharField(max_length=100)),
                ('service_provider_code', models.CharField(max_length=20)),
                ('hospital_identifier', models.BigIntegerField(default='1236547')),
                ('hospital_type', models.CharField(default='MultiSpeciality', max_length=100)),
                ('hospital_registration_number', models.BigIntegerField(default='568932')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('room_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_category_name', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC'), ('General', 'General')], max_length=50)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_scheduling.serviceprovider')),
            ],
        ),
    ]
